# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
GITHUB_KEY: 5991551eefc4ad2bf4d4
GITHUB_SECRET: b8ed71a82d661cfa03c7b211ab140b30ea23dc7c
FB_KEY: 1630653187251707
FB_SECRET: 35bc76b4ae414349dca1f318d2ba9fb7